apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-min-tls-version
  annotations:
    policies.kyverno.io/title: Enforce Minimum TLS Version
    policies.kyverno.io/category: Security, Network
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Ingress
    policies.kyverno.io/description: >-
      Enforces minimum TLS 1.2 for all Ingress resources. TLS 1.0 and 1.1 are
      deprecated and have known security vulnerabilities.
spec:
  validationFailureAction: Enforce
  background: true
  failurePolicy: Fail
  rules:
  - name: require-tls-12-ingress
    match:
      any:
      - resources:
          kinds:
          - Ingress
    preconditions:
      any:
      - key: "{{ request.object.spec.tls || '' }}"
        operator: NotEquals
        value: ""
    validate:
      message: >-
        Ingress resources with TLS must specify minimum TLS version 1.2 or 1.3
        via annotation 'nginx.ingress.kubernetes.io/ssl-protocols'.
      pattern:
        metadata:
          annotations:
            nginx.ingress.kubernetes.io/ssl-protocols: "TLSv1.2 TLSv1.3 | TLSv1.3"
  - name: auto-add-tls-version
    match:
      any:
      - resources:
          kinds:
          - Ingress
    preconditions:
      any:
      - key: "{{ request.object.spec.tls || '' }}"
        operator: NotEquals
        value: ""
      - key: "{{ request.object.metadata.annotations.\"nginx.ingress.kubernetes.io/ssl-protocols\" || '' }}"
        operator: Equals
        value: ""
    mutate:
      patchStrategicMerge:
        metadata:
          annotations:
            +(nginx.ingress.kubernetes.io/ssl-protocols): "TLSv1.2 TLSv1.3"
            +(nginx.ingress.kubernetes.io/ssl-ciphers): "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-secure-ingress
  annotations:
    policies.kyverno.io/title: Enforce Secure Ingress Configuration
    policies.kyverno.io/category: Security, Network
    policies.kyverno.io/severity: high
    policies.kyverno.io/description: >-
      Enforces security best practices for Ingress resources including TLS,
      HSTS, and secure cipher configuration.
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: require-tls-enabled
    match:
      any:
      - resources:
          kinds:
          - Ingress
          annotations:
            production: "true"
    validate:
      message: >-
        Production Ingress resources must have TLS enabled.
      pattern:
        spec:
          tls:
          - hosts:
            - "?*"
            secretName: "?*"
  - name: recommend-hsts
    match:
      any:
      - resources:
          kinds:
          - Ingress
    preconditions:
      any:
      - key: "{{ request.object.spec.tls || '' }}"
        operator: NotEquals
        value: ""
    validate:
      message: >-
        Ingress with TLS should enable HSTS (HTTP Strict Transport Security)
        via annotation 'nginx.ingress.kubernetes.io/force-ssl-redirect: true'.
      pattern:
        metadata:
          =(annotations):
            =(nginx.ingress.kubernetes.io/force-ssl-redirect): "true"
  - name: recommend-strong-ciphers
    match:
      any:
      - resources:
          kinds:
          - Ingress
    preconditions:
      any:
      - key: "{{ request.object.spec.tls || '' }}"
        operator: NotEquals
        value: ""
    validate:
      message: >-
        Consider using strong cipher suites via annotation
        'nginx.ingress.kubernetes.io/ssl-ciphers'.
      pattern:
        metadata:
          =(annotations):
            =(nginx.ingress.kubernetes.io/ssl-ciphers): "?*"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-service-tls
  annotations:
    policies.kyverno.io/title: Validate Service TLS Configuration
    policies.kyverno.io/category: Security, Network
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      Validates TLS configuration for Services with specific annotations.
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: validate-service-protocol
    match:
      any:
      - resources:
          kinds:
          - Service
          annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    validate:
      message: >-
        Internal load balancer services handling sensitive data should use
        annotation for backend protocol HTTPS.
      pattern:
        metadata:
          =(annotations):
            =(service.beta.kubernetes.io/azure-load-balancer-backend-protocol): "https | HTTPS"
