apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-provider
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: ""  # Set by workload identity
    keyvaultName: "${KEYVAULT_NAME}"
    cloudName: "AzurePublicCloud"
    tenantId: "${TENANT_ID}"
    objects: |
      array:
        - |
          objectName: model-encryption-key
          objectType: key
          objectVersion: ""
        - |
          objectName: inference-api-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: database-connection-string
          objectType: secret
          objectVersion: ""
        - |
          objectName: rl-training-credentials
          objectType: secret
          objectVersion: ""
  secretObjects:
    - secretName: kv-model-secrets
      type: Opaque
      data:
        - objectName: model-encryption-key
          key: MODEL_ENCRYPTION_KEY
        - objectName: inference-api-key
          key: INFERENCE_API_KEY
    - secretName: kv-db-secrets
      type: Opaque
      data:
        - objectName: database-connection-string
          key: DATABASE_CONNECTION_STRING
    - secretName: kv-training-secrets
      type: Opaque
      data:
        - objectName: rl-training-credentials
          key: RL_TRAINING_CREDENTIALS

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-tee-provider
  namespace: tee-workloads
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: ""  # Set by workload identity with TEE attestation
    keyvaultName: "${KEYVAULT_NAME}"
    cloudName: "AzurePublicCloud"
    tenantId: "${TENANT_ID}"
    # Attestation-gated access - requires valid TEE attestation token
    objects: |
      array:
        - |
          objectName: tee-model-decryption-key
          objectType: key
          objectVersion: ""
        - |
          objectName: tee-inference-secrets
          objectType: secret
          objectVersion: ""
        - |
          objectName: tee-training-secrets
          objectType: secret
          objectVersion: ""
  secretObjects:
    - secretName: tee-secure-secrets
      type: Opaque
      data:
        - objectName: tee-model-decryption-key
          key: TEE_MODEL_DECRYPTION_KEY
        - objectName: tee-inference-secrets
          key: TEE_INFERENCE_SECRETS
        - objectName: tee-training-secrets
          key: TEE_TRAINING_SECRETS
