apiVersion: v1
kind: ServiceAccount
metadata:
  name: keyvault-workload-identity
  namespace: default
  annotations:
    azure.workload.identity/client-id: "${WORKLOAD_IDENTITY_CLIENT_ID}"
    azure.workload.identity/tenant-id: "${TENANT_ID}"
    azure.workload.identity/use: "true"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keyvault-tee-workload-identity
  namespace: tee-workloads
  annotations:
    azure.workload.identity/client-id: "${TEE_WORKLOAD_IDENTITY_CLIENT_ID}"
    azure.workload.identity/tenant-id: "${TENANT_ID}"
    azure.workload.identity/use: "true"
    # TEE-specific annotations
    tee.attestation/required: "true"
    tee.attestation/provider: "azure-dcap"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keyvault-secrets-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["secrets-store.csi.x-k8s.io"]
    resources: ["secretproviderclasses"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keyvault-workload-identity-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keyvault-secrets-reader
subjects:
  - kind: ServiceAccount
    name: keyvault-workload-identity
    namespace: default
  - kind: ServiceAccount
    name: keyvault-tee-workload-identity
    namespace: tee-workloads

---
# Federated Identity Credential (applied via Azure CLI or Terraform)
# az identity federated-credential create \
#   --name keyvault-federated-identity \
#   --identity-name ${WORKLOAD_IDENTITY_NAME} \
#   --resource-group ${RESOURCE_GROUP} \
#   --issuer ${AKS_OIDC_ISSUER} \
#   --subject system:serviceaccount:default:keyvault-workload-identity \
#   --audience api://AzureADTokenExchange

# TEE Workload Federated Identity (with attestation claims)
# az identity federated-credential create \
#   --name tee-keyvault-federated-identity \
#   --identity-name ${TEE_WORKLOAD_IDENTITY_NAME} \
#   --resource-group ${RESOURCE_GROUP} \
#   --issuer ${AKS_OIDC_ISSUER} \
#   --subject system:serviceaccount:tee-workloads:keyvault-tee-workload-identity \
#   --audience api://AzureADTokenExchange
